- hosts: all
  vars_files:
          - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
  tasks:
  - name: "Install Web Server"
    package:
            name: "{{ p_name }}"
            state: present
  - name: "Create Web Pages in Doc Root"
    copy:
            content: "<h1> I am {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }} </h1> \n <h2> Task 14.3 Done by Karan Agrawal</h2>"
            dest: "{{ doc_root }}"

  - name: "Start Service"
    service:
            name: "{{ s_name }}"
            state: started

