- hosts: localhost
  vars_prompt:
  - name: c_name
    prompt: "Enter Container Name"
    private: false
  gather_facts: false
  tasks:
          
  - name: Creating Yum Repository for Docker
    yum_repository:
     name: docker
     description: Docker Repo
     file: /etc/yum.repos.d/docker
     baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
     gpgcheck: no
     enabled: true

  - name: Docker Package Installation
    command: "yum install docker-ce --nobest -y"

  - name: Install Software Python36
    package: 
     name: python3
     state: present

  - name: Install Docker Python Library
    pip:
     name: docker-py

  - name: Starting Docker Service
    service:
     name: docker
     state: started

  - name: Pull an Image
    docker_image:
     name: "karan757527/myimage:v3"
     source: pull

  - name: Creating Docker Container
    docker_container:
     name: "{{ c_name }}"
     image: "karan757527/myimage:v3"
     state: started
     detach: true
     interactive: true
     tty: true
     ports:
     - "1234:80"
  
  - name: Gathering Container Info
    docker_container_info:
            name: "{{ c_name }}"
    register: c_info

  - name: "Dynamically Updating IP in the Inventory"
    template:
     src: /root/inventory.j2
     dest: /inventory.txt

