- hosts: containers
  tasks:
   - name: "Installing HTTPD"
     package:
      name: httpd
      state: present

   - name: "Deploying Web Pages"
     copy:
      content: "<h1>Task 14.2</h1>\n<h2>Done by Karan Agrawal</h2>"
      dest: /var/www/html/index.html
  
   - name: "Starting Services"
     command: /usr/sbin/httpd
